version: '3.9'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command : mongod --noauth
    networks:
      - mongo_network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ynovroot
      MYSQL_DATABASE: ynovmsql
      MYSQL_USER: ynovuser
      MYSQL_PASSWORD: ynovpwd
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql_network

  backend_mongodb:
    build: ./archi_mongo
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - mongo_network

  backend_mysql:
    build: ./archi_mysql
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - mysql_network

  frontend:
    build: ./front
    ports:
      - "80:3000"
    depends_on:
      - backend_mongodb
      - backend_mysql
    networks:
      - mongo_network
      - mysql_network

volumes:
  mongodb_data:
  mysql_data:

networks:
  mongo_network:
    driver: bridge
  mysql_network:
    driver: bridge
