name: Build, Test and Deploy React Application

on:
  push:
    branches:
    - main

jobs:
  build_test:
    permissions:
        contents: write
        pull-requests: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci and test
        run: |
          cd front
          npm ci
          npm test  
      - name: Build all stacks
        run: docker-compose up -d
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build and docs
        run: |
          cd front
          npm run jsdoc
          npm run build --if-present
      - name: Push changes
        run: git push
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: front/build
          if-no-files-found: error
      

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    needs: build_test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2